// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhm9qWlu147jSijCeie703I6RJUUyEfGU',
    appId: '1:652295285755:web:5569b19aba1908b768b95e',
    messagingSenderId: '652295285755',
    projectId: 'postily-a7bd8',
    authDomain: 'postily-a7bd8.firebaseapp.com',
    storageBucket: 'postily-a7bd8.firebasestorage.app',
    measurementId: 'G-BBM5JX153W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcTVdelNcKMLTH-49gIBlZZRbPZ3MehIc',
    appId: '1:652295285755:android:412fe650fde4542668b95e',
    messagingSenderId: '652295285755',
    projectId: 'postily-a7bd8',
    storageBucket: 'postily-a7bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3nh5Fm-skyidpa8bffh0RyfH5YlestL0',
    appId: '1:652295285755:ios:8f710c3277ec344168b95e',
    messagingSenderId: '652295285755',
    projectId: 'postily-a7bd8',
    storageBucket: 'postily-a7bd8.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3nh5Fm-skyidpa8bffh0RyfH5YlestL0',
    appId: '1:652295285755:ios:8f710c3277ec344168b95e',
    messagingSenderId: '652295285755',
    projectId: 'postily-a7bd8',
    storageBucket: 'postily-a7bd8.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhm9qWlu147jSijCeie703I6RJUUyEfGU',
    appId: '1:652295285755:web:fb9caae43ebe816f68b95e',
    messagingSenderId: '652295285755',
    projectId: 'postily-a7bd8',
    authDomain: 'postily-a7bd8.firebaseapp.com',
    storageBucket: 'postily-a7bd8.firebasestorage.app',
    measurementId: 'G-STXPQJGJVL',
  );
}
